import type { OptimizedRoute, Trip } from "../types";

export const demoTrip: Trip = {
  id: "trip_tokyo_demo",
  name: "Tokyo Spring Route",
  description:
    "Four-day city itinerary focused on neighborhoods, food, and landmarks.",
  status: "draft",
  visibility: "private",
  startDate: "2026-04-10",
  endDate: "2026-04-14",
  places: [
    {
      tripPlaceId: "tp_tokyo_station",
      position: 1,
      dayNumber: 1,
      isLocked: true,
      notes: "Start here after hotel check-in.",
      place: {
        id: "place_tokyo_station",
        provider: "osm",
        providerPlaceId: "osm.tokyo_station",
        name: "Tokyo Station",
        address: "1 Chome Marunouchi, Chiyoda City, Tokyo",
        city: "Tokyo",
        country: "Japan",
        latitude: 35.6812,
        longitude: 139.7671,
        category: "Transit",
      },
    },
    {
      tripPlaceId: "tp_sensoji",
      position: 2,
      dayNumber: 1,
      isLocked: false,
      durationFromPreviousSeconds: 1080,
      place: {
        id: "place_sensoji",
        provider: "osm",
        providerPlaceId: "osm.sensoji",
        name: "Senso-ji",
        address: "2 Chome-3-1 Asakusa, Taito City, Tokyo",
        city: "Tokyo",
        country: "Japan",
        latitude: 35.7148,
        longitude: 139.7967,
        category: "Temple",
      },
    },
    {
      tripPlaceId: "tp_skytree",
      position: 3,
      dayNumber: 1,
      isLocked: false,
      durationFromPreviousSeconds: 720,
      place: {
        id: "place_skytree",
        provider: "osm",
        providerPlaceId: "osm.skytree",
        name: "Tokyo Skytree",
        address: "1 Chome-1-2 Oshiage, Sumida City, Tokyo",
        city: "Tokyo",
        country: "Japan",
        latitude: 35.7101,
        longitude: 139.8107,
        category: "Observation",
      },
    },
    {
      tripPlaceId: "tp_meiji",
      position: 4,
      dayNumber: 1,
      isLocked: false,
      durationFromPreviousSeconds: 2100,
      place: {
        id: "place_meiji",
        provider: "osm",
        providerPlaceId: "osm.meiji",
        name: "Meiji Shrine",
        address: "1-1 Yoyogikamizonocho, Shibuya City, Tokyo",
        city: "Tokyo",
        country: "Japan",
        latitude: 35.6764,
        longitude: 139.6993,
        category: "Shrine",
      },
    },
    {
      tripPlaceId: "tp_shibuya",
      position: 5,
      dayNumber: 1,
      isLocked: false,
      notes: "Best around blue hour.",
      durationFromPreviousSeconds: 840,
      place: {
        id: "place_shibuya",
        provider: "osm",
        providerPlaceId: "osm.shibuya",
        name: "Shibuya Crossing",
        address: "Shibuya City, Tokyo",
        city: "Tokyo",
        country: "Japan",
        latitude: 35.6595,
        longitude: 139.7004,
        category: "Landmark",
      },
    },
  ],
  latestRoute: null,
};

export const demoRoute: OptimizedRoute = {
  routeId: "route_tokyo_demo",
  tripId: demoTrip.id,
  algorithm: "nearest_neighbor",
  profile: "driving",
  orderedStops: demoTrip.places,
  summary: {
    totalDistanceMeters: 18400,
    totalDurationSeconds: 4740,
    matrixCacheHit: true,
    optimizationRuntimeMs: 4,
    providerRuntimeMs: 612,
  },
  geometry: {
    type: "LineString",
    coordinates: demoTrip.places.map((item) => [
      item.place.longitude,
      item.place.latitude,
    ]),
  },
};
